apiVersion: v1
kind: Service
metadata:
  name: mybio
  namespace: applications
  labels:
    app: mybio
    app.kubernetes.io/name: mybio
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: mybio-platform
spec:
  type: ClusterIP
  selector:
    app: mybio
  ports:
    - name: http
      port: 80
      targetPort: http
