apiVersion: v1
kind: Secret
metadata:
  name: mybio-secrets
  namespace: applications
type: Opaque
stringData:
  APP_SECRET: "replace-with-a-random-secret"
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ""
  SUPABASE_SERVICE_ROLE_KEY: ""
  CLOUDINARY_API_KEY: ""
  CLOUDINARY_API_SECRET: ""
